version: '3.8'

services:
  mqtt:
    build:
      context: ./mqtt
    container_name: mqtt_server
    ports:
      - "1883:1883"        # MQTT порт
      - "9001:9001"        # WebSocket порт (если понадобится)
    networks:
      - app_network

  app:
    build:
      context: ./app
    container_name: python_app
    depends_on:
      - mqtt
      - mongo
      - sql
      - neo4j
    networks:
      - app_network

  mongo:
    build:
      context: ./databases/mongo
    container_name: mongo_db
    ports:
      - "27017:27017"      # MongoDB порт
    networks:
      - app_network

  sql:
    image: postgres:13
    container_name: sql_db
    ports:
      - "5432:5432"        # PostgreSQL порт
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iot_data
    volumes:
      - ./databases/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  neo4j:
    build:
      context: ./databases/neo4j
    container_name: neo4j_db
    ports:
      - "7474:7474"        # HTTP интерфейс Neo4j
      - "7687:7687"        # Bolt интерфейс Neo4j
    environment:
      NEO4J_AUTH: neo4j/password
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
